# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FFmpeg
version:      0.01
version_from: FFmpeg.pm
installdirs:  site
requires:
    Inline:                        0.44
    Inline::C:                     0.44
    Time::Piece:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
